#!/usr/bin/env perl
# -*- comment-column: 40; -*-

use strict;
use warnings;

use Getopt::Long;
use Text::CSV;
use Time::Piece;
use Time::Seconds;
use File::Copy qw(copy);

use Data::Dumper;


our $LOGFILE = "$ENV{HOME}/.log/logfile.csv";
our $BACKUP  = $LOGFILE . ".bak";

# Create a CSV Parser Object
my $csv = Text::CSV->new({auto_diag => 1,
			  allow_whitespace => 1});

# Globals for Commandline Switches
our $DAYSAGO = 30; 
our $SUMMARY = 0;


# Validate Data is ISO format (YYYY-MM-DD)
sub validate_date {
    my ($date) = @_;

    # Check for an Exception
    eval {
        Time::Piece->strptime($date, '%Y-%m-%d');
    };

    # Return Negation of Exception Code
    return !$@;
}


# Make a backup of the log file
sub backup_log {

    copy($LOGFILE, $BACKUP)
	or die "Unable to create backup file: $!";

    print "Log file backed up: $BACKUP\n\n";    
}

# Read All Log Entries and return Array Ref
sub read_entries {

    my @entries;

    open my $fh, '<', $LOGFILE
	or die "Cannot open output file $LOGFILE.\n$!";

    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $value, $note) = @$row;

	push @entries, {
	    date     => $date,
	    activity => $activity,
	    value    => $value,
	    note     => $note,
	};
    }

    close $fh;

    return \@entries;
}


# Return Reference to a sorted Array of Dates
#    for a particular activity
sub get_activity_dates {

    my ($category) = @_;    

    my %dates;
    my $entries = read_entries();

    # Capture all dates matching $category
    for my $entry (@$entries) {
	next unless $entry->{activity} eq $category;
	$dates{$entry->{date}} = 1;
    }

    # Remove Dates from Hash and Return Ref
    my @days = sort keys %dates;

    return \@days;
}


# Print Longest Streak for Category
sub long_streak {

    my ($dates) = @_;

    return 1 if (@$dates == 1);	        # Single Entry
    
    my $streak  = 0;
    my $longest = 0;

    # Iterate through Dates List, Comparing Current and
    # Previous Dates to find Streaks
    my $prev  = Time::Piece->strptime($dates->[0], '%Y-%m-%d');
    
    for my $date (@$dates) {
	
	my $cur = Time::Piece->strptime($date, '%Y-%m-%d');
	my $del = ($cur-$prev)->days;

	if ($del == 1) {
	    $streak++;
	    $longest = $streak if ($streak > $longest);
	}
	else {
	    $streak = 1;
	    $longest = 1 if ($longest == 0);
	}

	$prev = $cur;
    }

    return $longest;
}


# Print Current Streak for Category
sub curr_streak {

    # Sort Dates in Reverse Order
    my ($dates_ref) = @_;
    my @dates = reverse @$dates_ref;

    my $streak = 0;

    # Iterate Through Dates Until a Day is Missed...
    my $prev  = Time::Piece->strptime($dates[0], '%Y-%m-%d');

    return $streak			# No current streak
	unless ((localtime() - $prev)->days < 2);

    for my $date (@dates) {	

	my $cur = Time::Piece->strptime($date, '%Y-%m-%d');
	my $del = ($prev-$cur)->days;

	return $streak if ($del > 1);

	$streak++;
	$prev = $cur;
    }

    return $streak;
}

# Print Longest and Current Streak Stats
sub streak {

    my ($category) = @_;
    my $dates = get_activity_dates($category);

    printf "The longest %s streak is: %i\n",
	$category, long_streak($dates);

    printf "The current %s streak is: %i\n",
	$category, curr_streak($dates);

    printf "Last logged %s: %s\n",
	$category, $dates->[-1];
}


# Add an entry to the log
sub add_entry {

    # Verify Args
    die "Four arguments are needed to add a record:\n" .
	"  -> date activity quantity units.\n" .
	"e.g. > add 20260704 read 30 pages\n"
	unless @_ == 4;

    my ($date, $activity, $quantity, $units) = @_;

    # Setup Date
    if ($date eq 'today') {
	$date = localtime->ymd;
    }
    elsif ($date eq 'yesterday') {
	my $yesterday = localtime() - ONE_DAY;
	$date = $yesterday->ymd;
    }
    else {
	die "Invalid date format: $date\n" .
	    "Should be: YYYY-MM-DD\n\n"
	    unless validate_date($date);
    }

    # Print to Logfile
    open my $fh, '>>', $LOGFILE
	or die "Cannot open output file $LOGFILE.\n$!";

    print $fh "$date,$activity,$quantity,$units\n";

    close $fh;
}


# Generate a list of all logged categories
sub print_categories {

    my %activities;
    
    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $value, $note) = @$row;

	$activities{$activity} += 1;
    }

    for (keys %activities) {

	printf "%-15s (%d entries)\n", $_, $activities{$_};
    }
}


# Print a Report for a Single Activity
sub report_category {

    # Category and Date Filters
    my ($category) = @_;
    my $cutoff = localtime() - (ONE_DAY * $DAYSAGO);

    # Summary Variables
    my ($count, $total);

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    printf "\n%s report for last %i days:\n", $category, $DAYSAGO;

    # Print Rows Meeting Date/Category Filter
    while (my $row = $csv->getline($fh)) {

	my ($date_str, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;

	next unless defined $date_str;
	my $date = Time::Piece->strptime($date_str, "%Y-%m-%d");
	next unless $date >= $cutoff;

	printf "  %10s: %5s %s\n", $date_str, $field1, $field2;
	$total += $field1; $count++;
    }

    # Print Summary Information
    if ($SUMMARY) {
	print "-----------------------------\n";
	printf "  Total: %i items\n  Sum: %i\n\n",
	    $count, $total;
    }

    close $fh;
}


# Handle Report Requests
sub report {

    return print_categories()
        unless @_;

    report_category(@_);
}


# Print 'Recent' Log Entires
sub recent {

    my $today = localtime();
    
    # Retrieve entries and sort them
    my $entries = read_entries();
    my @sorted =
	sort { $a->{date} cmp $b->{date} } @$entries;

    # Print Log Items from last 3 days...
    for my $entry (reverse @sorted) {

	my $date = Time::Piece->strptime(
	    $entry->{date}, "%Y-%m-%d");

	last if (($today - $date)->days > 3);

	printf "  %10s: %10s %5.1f %s\n", $entry->{date},
	    $entry->{activity}, $entry->{value}, $entry->{note};
    }
}


# Print an Intersection Report
sub intersect {

    my (@activities) = @_;

    die "Not enough categories for an intersection.\n"
	unless @activities >= 2;

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Build lookup tables for wanted categories and matches
    my %wanted = map {$_ => 1} @activities;
    my %days;
    
    # Find category matches and save them in a hash
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless exists $wanted{$activity};
	
	$days{$date}{$activity} = $field1;
    }

    close $fh;

    my $count = 0;
    
    # Print the intersections
    for my $day (sort keys %days) {

	my $match = 1;

	# Set $match flag if $activity is defined
	# for the given $day
	for my $activity (@activities) {
	    $match &&= exists $days{$day}{$activity};
	}

	next unless $match;		# Verify all categories

	$count++;
	
	printf "%-12s", $day;

	for my $activity (@activities) {
	    printf "%-5s", $days{$day}{$activity};
	}
	print "\n";	
    }

    print "There is no intersection for these categories.\n"
	unless $count;
}

# Find the maximum 'quantity' for an activity
sub maximum {

    my ($category) = @_;
    
    my $max = '-inf';
    my $max_date = "";

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Search for Maximum Value
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;
	
	if ($field1 > $max) {
	    $max = $field1;
	    $max_date = $date;
	}
    }
    close $fh;

    printf "max %s: %.1f on %s\n", $category, $max, $max_date;
}

# Find the minimum 'quantity' for an activity
sub minimum {

    my ($category) = @_;
    
    my $min = 'inf';
    my $min_date = "";

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Search for Minimum Value
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;
	
	if ($field1 < $min) {
	    $min = $field1;
	    $min_date = $date;
	}
    }
    close $fh;

    printf "Min %s: %.1f on %s\n", $category, $min, $min_date;
}


# Remove the last item added to the log
sub undo {

    my @lines;

    open my $in, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    @lines = <$in>;
    close $in;

    my $deleted = pop @lines;
    printf "Removed: %s", $deleted;

    open my $out, '>', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    print $out @lines;
    close $out;
}

# Print a friendly help message
sub help {

    print "You need serious help!\n";
}


# Main Program
sub main {

    # Handle Switches
    GetOptions(
	'last|l=i'    => \$DAYSAGO,
	'summary|s'   => \$SUMMARY,
	);

    # Check Need for Backups
    if (!-e $BACKUP || -M $BACKUP > 7) {
	backup_log();
    }
    
    # Handle Commands
    my $command = shift @ARGV
	or die "Usage: logit [add|report|intersect|max|min|help]\n";

    if ($command eq 'add') {	        # Add to the log
	add_entry(@ARGV);
    }
    elsif ($command eq 'report') {      # Generate report 
	report(@ARGV);
    }
    elsif ($command eq 'recent') {	# Print recent entries
	recent(@ARGV);
    }
    elsif ($command eq 'intersect') {   # Print intersection
	intersect(@ARGV);
    }
    elsif ($command eq 'backup') {	# Backup the Log
	backup_log();
    }
    elsif ($command eq 'streak') {      # Print Streaks 
	streak(@ARGV);
    }
    elsif ($command eq 'max') {	        # Maximum Event
	maximum(@ARGV);
    }
    elsif ($command eq 'min') {	        # Minimum Event 
	minimum(@ARGV);
    }				 
    elsif ($command eq 'help') {        # Print help 
	help(@ARGV);
    }
    elsif ($command eq 'undo') {        # Undo last add 
	undo(@ARGV);
    }
    else {
	die "unknown command: $command\n" .
	    "Usage: logit [add|report|intersect|max|min|help]\n";
    }
}

main();
