#!/usr/bin/env perl

# Local Variables:
# comment-column: 40
# End:

use strict;
use warnings;

use Time::Piece;
use Getopt::Long;
use Text::CSV;

use Data::Dumper;

our $LOGFILE = "$ENV{HOME}/.log/logfile.csv";

# Create a CSV Parser Object
my $csv = Text::CSV->new({auto_diag => 1,
			  allow_whitespace => 1});

# Timeframe for reports (default 30 days)
our $DAYSAGO = 30; 
our $ONEDAY  = 24 * 60 * 60;
our $SUMMARY = 0;

# Validate Data is ISO format (YYYY-MM-DD)
sub validate_date {
    my ($date) = @_;

    # Check for an Exception
    eval {
        Time::Piece->strptime($date, '%Y-%m-%d');
    };

    # Return Negation of Exception Code
    return !$@;
}


# Add an entry to the log
sub add_entry {

    # Verify Args
    die "Four arguments needed to add a record:\n" .
	"  -> date activity quantity units.\n" .
	"e.g. > add 20260704 read 30 pages\n"
	unless @_ == 4;

    my ($date, $activity, $quantity, $units) = @_;

    # Setup Date
    if ($date eq 'today') {
	$date = localtime->ymd;
    }
    elsif ($date eq 'yesterday') {
	my $yesterday = localtime() - $ONEDAY;
	$date = $yesterday->ymd;
    }
    else {
	die "Invalid date format: $date\n" .
	    "Should be: YYYY-MM-DD\n\n"
	    unless validate_date($date);
    }

    # Print to Logfile
    open my $fh, '>>', $LOGFILE
	or die "Cannot open output file $LOGFILE.\n$!";

    print $fh "$date,$activity,$quantity,$units\n";

    close $fh;
}


# Generate a list of all logged categories
sub print_categories {

    my %activities;
    
    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $value, $note) = @$row;

	$activities{$activity} += 1;
    }

    for (keys %activities) {

	printf "%-15s (%d entries)\n", $_, $activities{$_};
    }
}


# Print a Report for a Single Activity
sub report_category {

    # Category and Date Filters
    my ($category) = @_;
    my $cutoff = localtime() - ($ONEDAY * $DAYSAGO);

    # Summary Variables
    my ($count, $total);

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    printf "\n%s report for last %i days:\n", $category, $DAYSAGO;

    # Print Rows Meeting Date/Category Filter
    while (my $row = $csv->getline($fh)) {

	my ($date_str, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;

	next unless defined $date_str;
	my $date = Time::Piece->strptime($date_str, "%Y-%m-%d");
	next unless $date >= $cutoff;

	printf "  %10s: %5s %s\n", $date_str, $field1, $field2;
	$total += $field1; $count++;
    }

    # Print Summary Information
    if ($SUMMARY) {
	print "-----------------------------\n";
	printf "  Total: %i items\n  Sum: %i\n\n",
	    $count, $total;
    }

    close $fh;
}


# Handle Report Requests
sub report {

    return print_categories()
        unless @_;

    report_category(@_);
}


# Print an Intersection Report
sub intersect {

    my (@activities) = @_;

    die "Not enough categories for an intersection.\n"
	unless @activities >= 2;

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Build lookup tables for wanted categories and matches
    my %wanted = map {$_ => 1} @activities;
    my %days;
    
    # Find category matches and save them in a hash
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless exists $wanted{$activity};
	
	$days{$date}{$activity} = $field1;
    }

    close $fh;

    # Print the intersections
    for my $day (sort keys %days) {

	my $match = 1;

	for my $activity (@activities) {
	    $match &&= exists $days{$day}{$activity};
	}

	next unless $match;

	printf "%-12s", $day;

	for my $activity (@activities) {
	    printf "%-5s", $days{$day}{$activity};
	}

	print "\n";
    }
}

# Find the maximum quantity for an activity
sub maximum {

    my ($category) = @_;
    
    my $max = '-inf';
    my $max_date = "";

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Search for Maximum Value
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;
	
	if ($field1 > $max) {
	    $max = $field1;
	    $max_date = $date;
	}
    }

    close $fh;

    printf "max %s: %.1f on %s\n", $category, $max, $max_date;
}

# Find the minimum quantity for an activity
sub minimum {

    my ($category) = @_;
    
    my $min = 'inf';
    my $min_date = "";

    open my $fh, '<', $LOGFILE
	or die "Cannot open logfile: $LOGFILE.\n$!";

    # Search for Minimum Value
    while (my $row = $csv->getline($fh)) {

	my ($date, $activity, $field1, $field2) = @$row;

	next unless $activity eq $category;
	
	if ($field1 < $min) {
	    $min = $field1;
	    $min_date = $date;
	}
    }

    close $fh;

    printf "Min %s: %.1f on %s\n", $category, $min, $min_date;
}


# Print a friendly help message
sub help {

    print "You need serious help!\n";
}


# Main Program
sub main {

    # Handle Switches
    GetOptions(
	'last|l=i'    => \$DAYSAGO,
	'summary|s'   => \$SUMMARY,
	);

    # Handle Commands
    my $command = shift @ARGV
	or die "Usage: logit [add|report|help]\n";

    if ($command eq 'add') {	        # Add to the log
	add_entry(@ARGV);
    }
    elsif ($command eq 'report') {      # Generate report 
	report(@ARGV);
    }
    elsif ($command eq 'intersect') {   # Print intersection
	intersect(@ARGV);
    }
    elsif ($command eq 'max') {	        # Maximum Event
	maximum(@ARGV);
    }
    elsif ($command eq 'min') {	        # Minimum Event 
	minimum(@ARGV);
    }				 
    elsif ($command eq 'help') {        # Print help 
	help(@ARGV);
    }
    else {
	die "unknown command: $command\n" .
	    "Usage: logit [add|report|help]\n";
    }
}

main();
